# Generated by Django 4.2.2 on 2023-09-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_anime_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranimelist',
            old_name='Anime',
            new_name='anime',
        ),
    ]
