# Generated by Django 4.2.2 on 2023-09-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_rename_anime_useranimelist_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranimelist',
            name='myanimelist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='watchlist.anime'),
        ),
    ]
