# Generated by Django 4.2.2 on 2023-09-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_alter_useranimelist_myanimelist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimelist',
            name='myanimelist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
