# Generated by Django 4.2.2 on 2023-12-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0009_alter_useranimelist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimelist',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
