# Generated by Django 4.2.2 on 2023-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0012_alter_useranimelist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranimelist',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
