# Generated by Django 4.2.2 on 2024-01-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0013_alter_anime_score_alter_useranimelist_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='anime_type',
            new_name='genre',
        ),
    ]
