# Generated by Django 4.2.2 on 2024-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0016_remove_anime_genre_anime_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, to='watchlist.genre'),
        ),
    ]
