# Generated by Django 4.2.2 on 2024-01-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0017_remove_anime_genre_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='watchlist.genre'),
        ),
    ]
