# Generated by Django 4.2.2 on 2024-01-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0018_alter_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='watchlist.genre'),
        ),
    ]
