# Generated by Django 4.2.2 on 2024-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0020_alter_anime_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genre_tfidf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
