# Generated by Django 4.2.2 on 2024-01-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0021_anime_genre_tfidf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre_tfidf',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
