# Generated by Django 4.2.2 on 2024-01-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0022_alter_anime_genre_tfidf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre_tfidf',
        ),
    ]
