# Generated by Django 4.2.2 on 2024-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0023_remove_anime_genre_tfidf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, to='watchlist.genre'),
        ),
    ]
