# Generated by Django 4.2.2 on 2024-03-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0025_remove_anime_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='aired_on',
        ),
    ]
